const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  LEGAL_RISK_MANAGER: 'LEGAL_RISK_MANAGER',
  INTERNAL_AUDITOR: 'INTERNAL_AUDITOR',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  EXTERNAL_AUDITOR: 'EXTERNAL_AUDITOR',
  EXECUTIVE: 'EXECUTIVE'
};

const FRAMEWORKS = ['GDPR', 'HIPAA', 'ISO27001', 'SOC2'];

module.exports = { ROLES, FRAMEWORKS };
