const ROLES = {
  ADMIN: 'ADMIN',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  AUDITOR: 'AUDITOR',
  CONTROL_OWNER: 'CONTROL_OWNER',
  EMPLOYEE: 'EMPLOYEE',
  EXECUTIVE: 'EXECUTIVE'
};

module.exports = { ROLES };
